import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    backgroundColor: '#fff',
    borderRadius: 10,
    marginBottom: 12,
    paddingTop: 8,
    paddingBottom: 10,
    borderColor: '#2FDBBC',
    borderWidth: 2,
  },
  inlineContent: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    alignItems: 'center',
    width: '100%',
  },
  periodoContent: {
    flex: 1,
    width: 'auto',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#000',
    borderRadius: 10,
    padding: 4,
    margin: 8,
  },
  amostraContent: {
    flex: 1,
    width: 'auto',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#000',
    borderRadius: 10,
    padding: 4,
    margin: 8,
  },
  tituloText: {
    textAlign: 'center',
    fontSize: 16,
    fontWeight: 'bold',
    margin: 4,
  },
  subtituloText: {
    fontSize: 12,
    fontWeight: 'bold',
    textAlign: 'center',
  },
  contentText: {
    fontSize: 12,
    textAlign: 'center',
  },
  keyBedge: {
    fontSize: 16,
    fontWeight: 'bold',
    minWidth: 70,
    backgroundColor: '#078',
    color: '#fff',
    textAlign: 'center',
    borderRadius: 10,
    padding: 5,
  },
  statusBedge: {
    fontSize: 16,
    fontWeight: 'bold',
    minWidth: 70,
    backgroundColor: '#078',
    color: '#fff',
    textAlign: 'center',
    borderRadius: 10,
    padding: 5,
  },
  iconContainer: {
    position: 'absolute',
    top: 20,
    right: -20,
  },
});
